name: "brook"
port: "6001"
workers: "4"
log: "/Users/dx3/Library/Logs/BrookHttp"
gatekeeper: "/Users/dx3/Developer/storix/brook/gatekeeper.json"

beanstalkd:
  host: "127.0.0.1"
  port: "11301"

redis:
  host: "127.0.0.1"
  port: "6380"

